
service: auto-update-ecs-cluster-agent

custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.7
  timeout: 300
  memorySize: 128
  logRetentionInDays: 7
  region: ${opt:region, 'eu-west-1'}

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-log-retention
  - serverless-python-requirements
  - serverless-pseudo-parameters
package:
  exclude:
    - node_modules/**
    - samples/**
    - bin/**
    - include/**
    - lib/**
    - .vscode/
    - env/
    - .gitignore

functions:
  autoUpdateEcsClusterAgent:
    name: autoUpdateEcsClusterAgent
    timeout: 300
    memorySize: 120
    description: update ecs cluster agent for a container group node in a ecs cluster
    handler: lambda_handler.main
    iamRoleStatementsName: auto-update-ecs-cluster-agent-role
    iamRoleStatements:
      - Effect: Allow
        Action:
          - iam:CreateAccessKey
          - iam:DeleteAccessKey
          - iam:GetLoginProfile
          - iam:GetUser
          - iam:ListAccessKeys
          - iam:ListUsers
          - iam:UpdateLoginProfile
          - iam:ListUserTags
        Resource: "*"  
      - Effect: Allow
        Action:
          - sns:Publish
        Resource: "*"
    events:
      - schedule:
          name: auto-update-ecs-cluster-agent-schedule
          rate: rate(24 hours)
          enabled: true
    environment:
      AWS_REGION: eu-west-1
      AWS_SNS_RESULT_ARN: "<your sns topic "
      ECS_CLUSTER_NAME: "<your ecs cluster node>"
      ECS_GROUP_NODE: "<your ecs group node>"
      